# Conda environment specification. Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: deployment_env
dependencies:
  - python=3.10
  - scikit-learn=1.2  # actualiza a una versi칩n m치s reciente compatible con Python 3.10
  - numpy=1.24  # actualiza a una versi칩n m치s reciente compatible con Python 3.10
  - pip:
    - azureml-defaults==1.41.0
    - azureml-monitoring==0.1.0a18
    - inference-schema==1.0.2
    - inference-schema[numpy-support]==1.0.2
channels:
  - conda-forge
  - defaults
