# Conda environment specification. Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: deployment_env
dependencies:
  - python=3.10
  - scikit-learn=1.5.2  # Actualizado a la versión más reciente compatible con Python 3.10
  - numpy=2.1.3  # Versión más reciente de numpy compatible con Python 3.10
  - pip:
    - azureml-defaults==1.58.0  # Versión más reciente de azureml-defaults compatible con Python 3.10
    - azureml-monitoring==0.1.0a21 # Versión más reciente de azureml-monitoring
    - inference-schema==1.8 # Versión más reciente de azureml-schema
    - inference-schema[numpy-support] # sin versión...
channels:
  - defaults
  - anaconda # re-run
  - conda-forge
