# Conda environment specification. Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: training_env
dependencies:
  - python=3.10  # Asegúrate de usar Python 3.10
  - scikit-learn=1.2  # Actualizado a la versión más reciente compatible
  - matplotlib=3.6  # Actualizado a una versión compatible con Python 3.10
  - numpy=1.24  # Versión más reciente de numpy
  - pip:
    - azureml-defaults==1.41.0  # Versión más reciente de azureml-defaults compatible
channels:
  - conda-forge
  - defaults

